language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
  - "pypy"
install:
  - if [[ $TRAVIS_PYTHON_VERSION == '2.6' ]]; then pip install --use-mirrors unittest2; fi
  - pip install coverage coveralls --use-mirrors
script:
  - coverage erase
  - coverage run --source semidbm test_semidbm.py
notifications:
  email:
    - js@jamesls.com
after_success: coveralls
